testing-exceptiontester
testDoubleResume
	self assertSuccess: (ExceptionTester new runTest: #doubleResumeTest ) 