accessing
failBlock
	^ [ :exception | exception pass ]